### ISSUE TITLE
browserSync ?

### ISSUE THREAD

**Issue by guix77** [roots/roots#1285]
Hello,

I can see that for Sage you are using livereload like for Roots. Did you consider browserSync instead ? I'd be happy to help.

Cheers.

**Comment by austinpray** [comment]
Hey @guix77 

The only reason I am using livereload instead of browserSync is because it just works right out of the box without having to configure the proxy URL or anything. 

Now the manifest.json has a config property that can be optionally added:

```js
{
  // ...
  "config": {
    "url": "http://example.dev"
   }
}
```

And then feed that `manifest.config.url` to the browserSync proxy.

To get some discussion going:

Benefits:
  - browserSync is extremely dope. In case anyone is not familiar: http://www.browsersync.io/ I use it a lot these days.
  - do not have to enqueue livereload.js in assets.php

Drawbacks:
  - extra step to get people up and running, they have to edit the manifest.json with the correct url before `gulp watch` works.

**Comment by guix77** [comment]
Thank you for your kind answer Austin :)

I don't mind at all changing a few lines to use browserSync instead.

It seems to me also, that the primary target of Roots/Sage are highly-skilled professionals, and that those would rather use browserSync than liveReload. After all, it's just the local proxy URL to update, but the benefits are huge. Save any .less, .js or .php, and watch it happen on your phones, tablets, and TVs !

Just sayin' !

**Comment by austinpray** [comment]
I'm in favor of it because it reduces the need to enqueue livereload.js in lib/assets.php. Right now on the 8.0.0 branch if you visit the site without having `gulp watch` running livereload.js will 404 in your console. It is a benign 404, but still might be annoying and potentially disconcerting to noobs who don't know how livereload works.

In addition: exposes an external network URL so one can test on external devices that can't resolve example.dev for instance.

Sidenote: 
```js
{
  // ...
  "config": {
    "devUrl": "http://example.dev"
   }
}
```

What would that property be named? `url`, `devUrl`, `localUrl`?

**Comment by JulienMelissas** [comment]
Wow never used browserSync - looks awesome. I'll all for it, a config never hurt anyone, and we require true/false change anyways.

**Comment by austinpray** [comment]
@guix77 if you want to implement this, go ahead. We are going to go forward with browserSync.

**Comment by JulienMelissas** [comment]
@guix77 :+1: thanks for looking into it, if you don't want to take it on I may try and implement, just let us know.

**Comment by guix77** [comment]
Great ! First try here, then ! https://github.com/roots/roots/pull/1289

**Comment by austinpray** [comment]
FYI I have documented the "config" value in asset-builder: https://github.com/austinpray/asset-builder/commit/9b5e18b8f04d8d696999b4f1c06efdebb90f9533#diff-916b3e1e005fd96e3a0546715235477d

**Comment by retlehs** [comment]
thanks guys, this is awesome

**Comment by lukasbesch** [comment]
Wouldn't it be convenient to make BrowserSync use the `WP_HOME` value specified in the dotenv file of Bedrock if possible?

**Comment by QWp6t** [comment]
It's possible, but we're not likely to build it into Sage by default. It's too gimmicky and makes too many environmental assumptions beyond the scope of theme development.
