### ISSUE TITLE
Conditional check for templates isn't working correctly

### ISSUE THREAD

**Issue by webgurus** [roots/roots#1344]
Hello,

I've tried to set up a conditional check for sidebars to be hidden of several template files, but it doesn't work as it should.

This is my code and these templates don't show the sidebar anymore:
`[ 'is_page_template', ['template-contact.php','template-flexible.php', 'template-custom.php']],`

But it hides the sidebar for other page templates as well besides the default one.

Marton

**Comment by QWp6t** [comment]
Looks like you're doing it wrong. Pass those three template files as your second parameter.

```php
    $sidebar_config = new Roots_Sidebar(
      /**
       * Conditional tag checks (http://codex.wordpress.org/Conditional_Tags)
       * Any of these conditional tags that return true won't show the sidebar
       *
       * To use a function that accepts arguments, use the following format:
       *
       * array('function_name', array('arg1', 'arg2'))
       *
       * The second element must be an array even if there's only 1 argument.
       */
      array(
        'is_404',
        'is_front_page'
      ),
      /**
       * Page template checks (via is_page_template())
       * Any of these page templates that return true won't show the sidebar
       */
      array(
        'template-contact.php',
        'template-flexible.php',
        'template-custom.php'
      )
    );
```

You technically could do it by using `is_page_template` as part of the array in the first parameter, but you'd have to repeat it for each template, which I'm not going to demonstrate here because it's pointless.

You should take issues like this to http://discourse.roots.io/
